name: khipu_pay_plugin
description: "Plugin to create payment identifiers, process payments and verify the status of a payment through the Khipu Platform."
version: 2.0.1
homepage: https://github.com/juanvegu/khipu_pay_plugin

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: cl.duckytie.khipu_pay
        pluginClass: KhipuPay
      ios:
        pluginClass: KhipuPay
      web:
        pluginClass: KhipuPayWeb
        fileName: src/platform/web/khipu_pay_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
